# Terminal & colours
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# General
set -g mouse on
set -sg escape-time 10
set -g focus-events on
set -g history-limit 50000
set -g base-index 0
set -g pane-base-index 1
set -g renumber-windows on

# Key bindings
# Intuitive splits (keep current path)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
# Open new windows in current path
bind c new-window -c "#{pane_current_path}"

# Vi copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"

# Activity monitoring
set -g monitor-activity on
set -g visual-activity off
set -g window-status-activity-style "bg=colour1,fg=colour232"

set -g window-status-format "#I:#W#F"

# Pane borders
set -g pane-border-style "fg=colour253"
set -g pane-active-border-style "fg=colour206"

set -g window-style "bg=colour255,fg=colour0"
set -g window-active-style "bg=colour231"

# Status bar
set -g status-position top
set -g status-interval 10

set -g status-right "#[fg=colour44] RAM: #(~/.config/tmux/scripts/ram.sh) #[fg=colour255]|#[fg=colour200] %A %d %B %Y #[fg=colour255]#[fg=colour192,bold] [%H:%M]"

# Copy mode highlight
set -g mode-style "fg=white,bg=colour24"
