# Terminal & colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# General
set -g mouse on
set -sg escape-time 10
set -g focus-events on
set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Key bindings
# Intuitive splits (keep current path)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
# Open new windows in current path
bind c new-window -c "#{pane_current_path}"

# Vi copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"

# Activity monitoring
set -g monitor-activity on
set -g visual-activity off

# Pane borders
# Visible on light background: inactive grey, active dark blue
set -g pane-border-style "fg=colour250"
set -g pane-active-border-style "fg=colour24,bold"

set -g window-style "fg=#333333,bg=color255"
set -g window-active-style "fg=#333333,bg=color255"

# Status bar
set -g status-position top
set -g status-interval 5

set -g status-style "fg=colour255,bg=colour17"

set -g status-left "#[bold]#S#[nobold]  "

set -g window-status-format "#[fg=colour251]#I:#W#F#[default]"
set -g window-status-current-format "#[bold,bg=colour38,fg=colour255] #I:#W#F #[default]"
set -g window-status-activity-style "fg=colour10"

set -g status-right "#[fg=colour44,bold] RAM: #(~/.config/tmux/scripts/ram.sh) #[fg=colour255]|#[fg=colour200] %A %d %B %Y #[fg=colour255]#[fg=colour192] [%H:%M]"

# Copy mode highlight
set -g mode-style "fg=white,bg=colour24"
